### ISSUE TITLE
Screen only locks once until reboot

### ISSUE THREAD

**Issue by pbbob** [the-cavalry/light-locker#148] opened 2019-09-21 17:07 UTC
I am using ArchLinux:
light-locker 1.8.0-2
lightdm 1:1.30.0-2
linux 5.3.arch1-1

Recently, (I think after a package upgrade, cant remember for sure), lightlocker stopped working correctly. If I log in to my computer after a fresh reboot, I am able to lock the screen once, however when I log in after that, I cannot lock it again until I reboot. When I try to lock it after the first time, the screen just displays the message "The session is locked, You’ll be redirected to the unlock dialog in a few seconds." And doesn't do anything.

**Comment by newrokor** [comment] 2019-09-22 11:12
I can confirm this using the same system. Logging into another virtual terminal and killing light-locker brings back the locked session. The ability to lock the session is gone then, of course, but starting light-locker again, brings back the same effect. The session can be locked/unlocked once, but not a second time.

Direct dependencies of light-locker in Arch are dbus-glib  gtk3  libxxf86misc  lightdm  libxss. The installations of these packages are quite old with the exception of gtk3, updated on Sep 7 to 3.24.11. I have not checked right now, if a downgrade to 3.24.10 removes the problem.

**Comment by newrokor** [comment] 2019-09-22 13:45
No, it is not gtk3, but a downgrade of systemd from 243.0 to 242.84 does the trick, however, for obvious reasons this is only an intermediate work around.

**Comment by chrishoage** [comment] 2019-09-22 18:25
Duplicate of https://github.com/the-cavalry/light-locker/issues/146

**Closed as completed** 2019-09-22 20:25 UTC
