### ISSUE TITLE
Configure failure on Arch Linux with systemd 229

### ISSUE THREAD

**Issue by bjo81** [the-cavalry/light-locker#79] opened 2016-03-16 23:18 UTC
Configure tells me:

checking for SYSTEMD... no
configure: error: Systemd support explicitly required, but systemd not found

but systemd is installed:
local/libsystemd 229-3
    systemd client libraries
local/systemd 229-3
    system and service manager

**Comment by andreyv** [comment] 2016-03-21 15:25
Full error from `config.log`:

```
configure:16767: checking for SYSTEMD
configure:16774: $PKG_CONFIG --exists --print-errors "libsystemd-login"
Package libsystemd-login was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsystemd-login.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsystemd-login' found
configure:16777: $? = 1
configure:16791: $PKG_CONFIG --exists --print-errors "libsystemd-login"
Package libsystemd-login was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsystemd-login.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsystemd-login' found
configure:16794: $? = 1
configure:16808: result: no
No package 'libsystemd-login' found
configure:16849: error: Systemd support explicitly required, but systemd not found
```

`libsystemd-login` functionality was merged into `libsystemd` in systemd 209: https://github.com/systemd/systemd/blob/v209/NEWS#L225. Since then `libsystemd-login` has been a compatibility library only.

And with systemd 229 Arch Linux finally stopped building the compatibility libraries: https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/systemd&id=c91d52bcf82e197f3ea217893e20e45e43f933b7

**Comment by andreyv** [comment] 2016-03-21 15:30
Looks like this is a duplicate of #64.

**Comment by cavalier38** [comment] 2017-06-07 19:42
Changed to support systemd > 209 which was already patched by various distributions 97c2b9

**Closed by cavalier38** 2017-06-07 19:42 UTC
